# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- master

pool:
  vmImage: 'windows-latest'
  
steps:
- task: UseDotNet@2
  displayName: 'Use dotnet sdk 3.1'
  inputs:
    version: 3.1.x
    installationPath: '$(Agent.ToolsDirectory)/dotnet'

# Dotnet 2.1 appears to be required for ESRP signing? seems weird, testing
- task: UseDotNet@2
  displayName: 'Use dotnet sdk 2.1'
  inputs:
    version: 2.1.x
    installationPath: '$(Agent.ToolsDirectory)/dotnet'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)/src/PASopa.sln'
    arguments: '--configuration $(BuildConfiguration) -p:BinPath=$(Build.BinariesDirectory)/'
    
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '**\PAModelTests.dll'
    searchFolder: '$(Build.BinariesDirectory)'
    runInParallel: true
    codeCoverageEnabled: true
    configuration: '$(BuildConfiguration)'

- task: EsrpCodeSigning@1
  inputs:
    ConnectedServiceName: 'ESRP Android Code Signing'
    FolderPath: '$(Build.BinariesDirectory)/$(BuildConfiguration)/PAModel/'
    Pattern: '*.dll'
    signConfigType: inlineSignParams
    inlineOperation: |
     [
         {
             "keyCode": "CP-230012",
             "operationSetCode": "SigntoolSign",
             "parameters": [
             {
                 "parameterName": "OpusName",
                 "parameterValue": "Microsoft"
             },
             {
                 "parameterName": "OpusInfo",
                 "parameterValue": "http://www.microsoft.com"
             },
             {
                 "parameterName": "Append",
                 "parameterValue": "/as"
             },
             {
                 "parameterName": "FileDigest",
                 "parameterValue": "/fd \"SHA256\""
             },
             {
                 "parameterName": "PageHash",
                 "parameterValue": "/NPH"
             },
             {
                 "parameterName": "TimeStamp",
                 "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
             }
             ],
             "toolName": "sign",
             "toolVersion": "1.0"
         }
     ]
    ServiceEndpointUrl: 'https://api.esrp.microsoft.com/api/v1'