# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- master

pool:
  vmImage: 'windows-latest'
  
steps:
- task: UseDotNet@2
  displayName: 'Use dotnet sdk 3.1'
  inputs:
    version: 3.1.x
    installationPath: '$(Agent.ToolsDirectory)\dotnet'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)/src/PASopa.sln'
    arguments: '--configuration $(BuildConfiguration) -p:BinPath="$(Build.BinariesDirectory)\"'
    
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '**\PAModelTests.dll'
    searchFolder: '$(Build.BinariesDirectory)'
    runInParallel: true
    codeCoverageEnabled: true
    configuration: '$(BuildConfiguration)'
