# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
# - task: NuGetCommand@2
#   displayName: 'Restore PowerApps.Tools Package'
#   inputs:
#     restoreSolution: src/Nuget/packages.tools.config
#     vstsFeed: '7a557a84-8b01-4ea1-bce5-e88f70976347'
#     includeNuGetOrg: false
#     restoreDirectory: '$(Agent.BuildDirectory)/p/'

# - task: PowerShell@1
#   displayName: 'Set PowerApps.Tools Package Path'
#   inputs:
#     scriptType: inlineScript
#     inlineScript: |
#      $result = [System.IO.File]::ReadAllText("$(Build.SourcesDirectory)/src/Nuget/packages.tools.config") | `
#      Select-Xml -XPath "/packages/package[@id='PowerApps.Tools']" | `
#      Select-Object -First 1
#      $version = $result.Node.version
     
#      $path = "$(PackagesPath)\PowerApps.Tools.$version"
#      Write-Host "##vso[task.setvariable variable=ToolsPackagePath]$path"
- task: UseDotNet@2
  displayName: 'Use dotnet sdk 3.1'
  inputs:
    version: 3.1.x
    installationPath: '$(Agent.ToolsDirectory)/dotnet'

# Dotnet 2.1 appears to be required for ESRP signing? seems weird, testing
- task: UseDotNet@2
  displayName: 'Use dotnet sdk 2.1'
  inputs:
    version: 2.1.x
    installationPath: '$(Agent.ToolsDirectory)/dotnet'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)/src/PASopa.sln'
    arguments: '--configuration $(BuildConfiguration) -p:BinPath=$(Build.BinariesDirectory)/'
    
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '**\PAModelTests.dll'
    searchFolder: '$(Build.BinariesDirectory)'
    runInParallel: true
    codeCoverageEnabled: true
    configuration: '$(BuildConfiguration)'

- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  inputs:
    ConnectedServiceName: 'ESRPCodeSigningConnection'
    FolderPath: '$(Build.BinariesDirectory)/$(BuildConfiguration)/PAModel/'
    Pattern: '*.dll'
    signConfigType: inlineSignParams
    inlineOperation: |
     [
         {
             "keyCode": "CP-233863-SN",
             "operationSetCode": "StrongNameSign",
             "parameters": [ ],
             "toolName": "sign",
             "toolVersion": "1.0"
         },
         {
             "keyCode": "CP-230012",
             "operationSetCode": "SigntoolSign",
             "parameters": [
             {
                 "parameterName": "OpusName",
                 "parameterValue": "Microsoft"
             },
             {
                 "parameterName": "OpusInfo",
                 "parameterValue": "http://www.microsoft.com"
             },
             {
                 "parameterName": "Append",
                 "parameterValue": "/as"
             },
             {
                 "parameterName": "FileDigest",
                 "parameterValue": "/fd \"SHA256\""
             },
             {
                 "parameterName": "PageHash",
                 "parameterValue": "/NPH"
             },
             {
                 "parameterName": "TimeStamp",
                 "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
             }
             ],
             "toolName": "sign",
             "toolVersion": "1.0"
         },
         {
             "keyCode": "CP-233863-SN",
             "operationSetCode": "StrongNameVerify",
             "parameters": [ ],
             "toolName": "sign",
             "toolVersion": "1.0"
         }
     ]
    ServiceEndpointUrl: 'https://api.esrp.microsoft.com/api/v1'