# CI workflow for PRs and merges to master
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    env:
      DOTNET_NOLOGO: true

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          3.1.x
          6.0.x

    - run: dotnet --info

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: csharp

    - name: Build and test (win)
      run: ./build ci
      shell: cmd
      if: ${{ runner.os == 'Windows' }}

      ## Only difference here is not forcing cmd
    - name: Build and test (!win)
      run: ./build ci
      if: ${{ runner.os != 'Windows' }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
