# CI workflow for PRs and merges to master
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    env:
      DOTNET_NOLOGO: true

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Build and test (win)
      run: ./build ci
      if: ${{ runner.os == 'Windows' }}

    - name: Build only (!win)
      run: ./build rebuild
      # 4 out of 15 tests fail when running on e.g. linux (WSL-Debian)
      if: ${{ runner.os != 'Windows' }}
