# CI workflow for PRs and merges to master
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    env:
      DOTNET_NOLOGO: true

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          7.0.x

    - run: dotnet --info

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: csharp

    - name: Build and test (win)
      run: ./build ci
      shell: cmd
      if: ${{ runner.os == 'Windows' }}

      ## Only difference here is not forcing cmd
    - name: Build and test (ubuntu & macos)
      run: ./build ci
      if: ${{ runner.os != 'Windows' }}

    - name: Test - Persistence
      run: dotnet bin/Debug/Persistence.Tests/Persistence.Tests.dll

    - name: Test - PAModel
      run: dotnet bin/Debug/PAModelTests/PAModelTests.dll

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
